### PR TITLE
Update roles to LSMB master commit c6fd6e533.

### PR DESCRIPTION
**Pull request by neilt**
It would be nice if the descriptions could to be added before this PR is merged. At least the non-obvious  ones. For example, "recurring" or "contact_class_employee".

### CODE REVIEW

**Comment by ehuelsmann** [comment]
Wow. That's quite a list of change. Should we list the ones obsoleted in versions earlier than 1.9? Or should we just remove those? (That is, if the role has been removed from the system...)

**Comment by neilt** [comment]
Yeah, I noticed that when I first started verifying the list that I just deleted some, then later on I started marking them Obsolete.  I was not sure which would be better.

The easiest way for me is to delete all that do not appear as current pg roles as that is what I compared against.  I do not know that I have the knowledge or time to figure out which ones were pre 1.9.

**Comment by ehuelsmann** [comment]
> The easiest way for me is to delete all that do not appear as current pg roles as that is what I compared against. I do not know that I have the knowledge or time to figure out which ones were pre 1.9.

Then lets just document it's the list as it applies to 1.10 - which may miss older roles and add new ones. Then, maybe, later I can generate a list from 1.9 and we can document the dropped ones and how they map to new ones -- if applicable.

**Comment by neilt** [comment]
> > The easiest way for me is to delete all that do not appear as current pg roles as that is what I compared against. I do not know that I have the knowledge or time to figure out which ones were pre 1.9.
> 
> Then lets just document it's the list as it applies to 1.10 - which may miss older roles and add new ones. Then, maybe, later I can generate a list from 1.9 and we can document the dropped ones and how they map to new ones -- if applicable.

I had not thought comparing version would be that simple, but of course it is.  How about I create the master for the various versions and you add descriptions.

**Comment by ehuelsmann** [comment]
>
> I had not thought comparing version would be that simple, but of course it
> is. How about I create the master for the various versions and you add
> descriptions.
>
Works for me.

**Pull request merged**
